services:
  traefik:
    image: traefik:v2.3
    restart: unless-stopped
    ports:
      - "80:80" # 2, 3
      - "443:443" # 2, 3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # 2, 3
      - traefik-public-certificates:/certificates # 2, 3
    command:
      - --providers.docker # 2, 3
      - --providers.docker.exposedbydefault=false # 2, 3
      - --entrypoints.http.address=:80 # 2, 3
      - --entrypoints.https.address=:443 # 2, 3
      - --certificatesresolvers.le.acme.email=ivan.kudashkin@gmail.com # 2, 3
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json # 2
      - --certificatesresolvers.le.acme.tlschallenge=true # 2
      - --accesslog # 2, 3
      - --log # 2
    networks:
      - traefik-public # 2

volumes:
  traefik-public-certificates: # 2, 3

networks:
  traefik-public: # 2
    external: true # 2
