services:
  fastapi:
    build: ./
    restart: unless-stopped
#    ports: # old
#      - "80:80" # old, for local deployment
    labels:
      - traefik.enable=true # 2, 3
      - traefik.http.services.app.loadbalancer.server.port=80 # 2
      - traefik.http.routers.app-http.entrypoints=http # 2
      - traefik.http.routers.app-http.rule=Host(`ivankud.com`) # 2, 3
      - traefik.docker.network=traefic-public
#      - traefik.http.routers.app-http.tls=true # 3
#      - traefik.http.routers.app-http.tls.certresolver=letsencrypt # 3
    networks:
      - traefic-public # 2

  traefik:
#    image: traefik:v2.2 # 1 digitalocean
    image: traefik:v2.3 # 2 tiangolo
#    image: traefik:v2.3 # 3 towardsDS
#    image: traefik:v2.8 # 4 unixhost
    restart: unless-stopped
    ports:
      - "80:80"
#      - "443:443" # 3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # 2, 3
#      - $PWD/services/traefik/traefik.toml:/etc/traefik/traefik.toml # 3
#      - traefik-public-certificates:/certificates # 3
    command:
      - --providers.docker # 2
      - --providers.docker.exposedbydefault=false # 2
      - --entrypoints.http.address=:80 # 2
      - --accesslog # 2
      - --log # 2
    networks:
      - traefic-public # 2

networks:
  traefic-public: # 2
    external: true # 2
#    external: false # for local deployment

#volumes:
#  traefik-public-certificates: # 3
